# Generated by Django 4.1.5 on 2023-01-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2app', '0002_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='name1',
        ),
    ]
