# Generated by Django 4.1.5 on 2023-02-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2app', '0003_rename_desc_actor_desc1_rename_img_actor_img1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='actor',
        ),
    ]
